services:
  - type: web
    name: agri-dashboard-backend
    env: python
    plan: free
    branch: main
    repo: https://github.com/Akanscode/agri-dashboard
    buildCommand: pip install -r backend/requirements.txt
    startCommand: bash backend/start.sh
    autoDeploy: true
